CREATE TABLE Employees(
[UserId] INT IDENTITY (1,1) NOT NULL PRIMARY KEY ,
[Name] NVARCHAR (500) NOT NULL,
[Email] NVARCHAR (500) NOT NULL,
[Password] NVARCHAR(500) NOT NULL,
[Phone] INT NOT NULL,

);


