CREATE TABLE Employee(
[EmployeeId]  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[Name] NVARCHAR(500) NOT NULL,
[Phone] NVARCHAR(10) NOT NULL,
[Email] NVARCHAR(500) NOT NULL,
[Password] NVARCHAR(50) NOT NULL,

);

SELECT * FROM Employee;