CREATE TABLE Books(
[BooksId] int IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Book_Name] NVARCHAR(100) NOT NULL,
[Category] NVARCHAR(100) NOT NULL,
[Author] NVARCHAR(100) NOT NULL,
[Publisher] NVARCHAR (100) NOT NULL,
[Edition] NVARCHAR(100) NOT NULL,
[ISBN] NVARCHAR(13) NOT NULL,
[Published_Date] DATE NOT NULL
);


SELECT * FROM Books;

ALTER TABLE Books
ALTER COLUMN ISBN VARCHAR(20);
