ALTER TABLE MEMBER
ADD Member_Type NVARCHAR(50);

ALTER TABLE MEMBER
ALTER COLUMN Member_Type NVARCHAR(30) NOT NULL;

UPDATE Member
SET Member_Type='Standard';

DELETE FROM		Member
WHERE UserId = 2002;